apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger-np
    release: istiod
  name: jaeger
  namespace: istio-system
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30004
  selector:
    app.kubernetes.io/name: jaeger
  sessionAffinity: None
  type: NodePort
