apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: amf
  labels:
    app: amf
    version: pro
spec:
  selector:
    matchLabels:
      app: amf
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: amf
        version: pro
    spec:
      containers:
      - name: amf
        image:  mangarcg/amf:v1.0.1
        ports:
        - containerPort: 2000

---

apiVersion: v1
kind: Service
metadata:
  name: amf
spec:
  selector:
    app: amf
  ports:
    - name: http
      protocol: TCP
      port: 2000
      targetPort: 2000
---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: amf
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - amf.k8s.intra.local
    secretName: none-cert
  rules:
  - host: amf.k8s.intra.local
    http:
      paths:
      - path: /
        backend:
          serviceName: amf
          servicePort: 2000

